export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";

export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

export const SET_RECIPES = "SET_RECIPES";
export const SET_RECIPE = "SET_RECIPE";
export const LOADING_DATA = "LOADING_DATA";
export const LIKE_RECIPE = "LIKE_RECIPE";
export const UNLIKE_RECIPE = "UNLIKE_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const POST_RECIPE = "POST_RECIPE";
